// RSS sources

export const sources : Record<string, string> = {
  // "知乎每日精选" : "https://www.zhihu.com/rss",
  // "知乎日报" : "https://rsshub.app/zhihu/daily",
  // "知乎热榜" : "https://rsshub.app/zhihu/hot/",
  // "外交动态" : "https://rsshub.app/gov/mfa/wjdt/fyrbt",
  // "Elon Musk" : "https://rsshub.app/twitter/user/elonmusk",
  // "Bill Gates" : "https://rsshub.app/twitter/user/billgates",
  // "Tim Cook" : "https://rsshub.app/twitter/user/tim_cook",
  // "Jeff Bezos" : "https://rsshub.app/twitter/user/jeffbezos",
  // "The Verge" : "https://www.theverge.com/rss/frontpage",
  // "电丸科技AK" : "https://rsshub.app/youtube/channel/UCZVThl_MRppEdGUPGjXSSdg",
  // "Netflix" : "https://rsshub.app/netflix/newsroom",
  // "小鹿Lawrence" : "https://rsshub.app/bilibili/user/video/37029661",
  // "米老师呀" : "https://rsshub.app/bilibili/user/video/9504837",
  "GitHub" : `https://github.com/SugarmanZhu.private.atom?token=${process.env.GITHUB_TOKEN}`,
  // "GitHub" : "https://github.com/sugarmanzhu.atom",
  // "新浪创事记" : "https://rsshub.app/sina/csj",
  // "央视新闻" : "https://rsshub.app/cctv/xwlb",
  // "微软亚洲研究院" : "https://msra.cn/feed",
  // "MIT Technology Review" : "https://www.technologyreview.com/feed/",
  // "TechCrunch" : "https://techcrunch.com/feed",
  // "Mashable" : "https://mashable.com/feeds/rss/all",
  // "Wired" : "https://www.wired.com/feed/rss",
  // "The New York Times" : "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
  // "BBC News" : "http://feeds.bbci.co.uk/news/technology/rss.xml",
}